services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d its"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./postgres/initdb:/docker-entrypoint-initdb.d
    networks:
      - main_network

  learningservice:
    build:
      context: learningservice
    ports:
      - "127.0.0.1:8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - learningservice/.env.example
    environment:
      - DATABASE_HOST=postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - main_network

  teachingservice:
    build:
      context: teachingservice
    ports:
      - "127.0.0.1:8082:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - teachingservice/.env.example
    environment:
      - DATABASE_HOST=postgres
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q --spider http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - main_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - "127.0.0.1:8083:8080"
      - "9002:9000"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
      KC_HEALTH_ENABLED: true
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: 'true'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
    command: start-dev
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - main_network

  minio:
    image: minio/minio:latest
    ports:
      - "127.0.0.1:9000:9000"
      - "127.0.0.1:9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: iamadmin
    entrypoint: sh
    command: -c 'mkdir -p /data/its && minio server --address ":9000" --console-address ":9001" /data'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data
    networks:
      - main_network

  nginx:
    # image: nginx:latest
    build:
      context: nginx
    ports:
      - "8080:80"
    environment:
      OIDC_DISCOVERY: "http://keycloak:8080/realms/intellilearn/.well-known/openid-configuration"
      OIDC_CLIENT_ID: "nginx"
      OIDC_ACCEPTED_AUDIENCES: "nginx"
      OIDC_SSL_VERIFY: "false"
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./nginx/lua:/usr/local/openresty/lualib/app:ro 
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    depends_on:
      learningservice:
        condition: service_healthy
      teachingservice:
        condition: service_healthy
    networks:
      - main_network

volumes:
  postgres_data:
  minio_data:

networks:
  main_network:
