spring:
  application:
    name: learningservice
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/its
    username: admin
    password: admin
  security:
    user:
      name: admin
      password: admin

keycloak:
  server-url: http://127.0.0.1:8083/
  realm: intellilearn
  client-id: nginx
  client-secret: "w5upehqrRr3xTL57IRAX0Vn5U6zGitbr"

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 18080
  servlet:
    context-path: /api/v1