env OIDC_JWKS_URI;
env OIDC_CLIENT_ID;
env OIDC_SSL_VERIFY;

worker_processes 3;

events {
  worker_connections 1024;
}

http {
  resolver 127.0.0.11 valid=30s ipv6=off;
  lua_package_path "/usr/local/openresty/lualib/app/?.lua;/usr/local/openresty/lualib/?.lua;;";

  lua_shared_dict oidc_cache 10m;
  lua_shared_dict jwks_cache 10m;

  include mime.types;
    
  upstream learningservice {
    server learningservice:8080;
  }

  upstream teachingservice {
    server teachingservice:8080;
  }

  server {
    listen 80;
    server_name localhost;

    location /learning/ {
      access_by_lua_file /usr/local/openresty/lualib/app/validate_oidc.lua;
      proxy_pass http://learningservice/api/v1/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /teaching/ {
      access_by_lua_file /usr/local/openresty/lualib/app/validate_oidc.lua;
      proxy_pass http://teachingservice/api/v1/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }
  }
}