spring:
  application:
    name: teachingservice
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/its
    username: postgres
    password: 2210254
  security:
    user:
      name: admin
      password: admin

keycloak:
  server-url: http://127.0.0.1:8083/
  realm: intellilearn
  client-id: nginx
  client-secret: "w5upehqrRr3xTL57IRAX0Vn5U6zGitbr"

management:
  endpoints:
    web:
      exposure:
        include: health,info
server:
  port: 28080
  servlet:
    context-path: /api/v1

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: iamadmin
  bucket-name: its